# Generated by Django 2.2.13 on 2021-02-12 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picha', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Picha',
            new_name='Picture',
        ),
    ]
